# Generated by Django 4.1.6 on 2023-03-12 07:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default=accounts.models.get_default_resume, upload_to=accounts.models.use_directory_path),
        ),
    ]
