# Generated by Django 4.1.6 on 2023-06-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
