# Generated by Django 4.1.6 on 2023-03-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_details', models.TextField(default='Job details to come.')),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('posted', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField()),
            ],
        ),
    ]
