# Generated by Django 4.1.6 on 2023-06-13 02:29

from django.conf import settings
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='covering_letter',
            field=models.FileField(upload_to=jobs.models.use_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='applied',
            unique_together={('applicant', 'job')},
        ),
    ]
