# Generated by Django 4.1.6 on 2023-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpositions_job_summary_jobpositions_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositions',
            name='slug',
            field=models.SlugField(default='placeholder'),
        ),
    ]
